# Generated by Django 2.2.5 on 2019-09-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'LUNES'), ('M', 'MARTES'), ('W', 'MIERCOLES'), ('J', 'JUEVES'), ('V', 'VIERNES'), ('S', 'SABADO'), ('D', 'DOMINGO')], max_length=40)),
                ('hora', models.TimeField()),
                ('vueloId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_search.Vuelo')),
            ],
        ),
    ]
