# Generated by Django 2.2.5 on 2019-09-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_search', '0004_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('TARJETA_CREDITO', 'TC'), ('TARJETA_DEBITO', 'TD')], max_length=40)),
                ('fecha', models.DateField()),
                ('vencimiento', models.DateField()),
                ('propietarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_search.Pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_search.Pago')),
                ('tarjetaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_search.Tarjeta')),
            ],
        ),
    ]
