# Generated by Django 2.2.5 on 2019-09-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_search', '0005_pagotarjeta_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerario',
            name='dia',
            field=models.CharField(choices=[('Mon', 'LUNES'), ('Tue', 'MARTES'), ('Wed', 'MIERCOLES'), ('Thu', 'JUEVES'), ('Fri', 'VIERNES'), ('Sat', 'SABADO'), ('Sun', 'DOMINGO')], max_length=40),
        ),
    ]
